# Generated by Django 3.1.5 on 2021-01-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_direction',
        ),
    ]
