# Generated by Django 3.1.5 on 2021-01-13 08:38

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0002_delete_all_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, verbose_name='username')),
                ('FIO', models.CharField(max_length=120, verbose_name='FIO')),
                ('2000-10-14', models.DateField(verbose_name='data')),
                ('address', models.CharField(max_length=120, verbose_name='address')),
                ('place_of_study', models.CharField(max_length=200, verbose_name='place_of_study')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('all_Direction_id', models.ManyToManyField(to='my_app.All_Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('all_diriction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.all_direction')),
            ],
        ),
    ]
